baseURL = 'https://mfreimueller.com/'
languageCode = 'de'
title = 'Michael Freimüller'
Copyright = 'Copyright © 2023 Michael Freimüller'

[Params]
author = 'Michael Freimüller'
ShowThemeInfo = true

[mediaTypes]
[mediaTypes.'application/rss+xml']
suffixes = ['xml']
